query HeadToHead($name1: String!, $name2: String!, $excludeMidis: Boolean!) {
  headToHead(name1: $name1, name2: $name2, excludeMidis: $excludeMidis) {
    wins
    losses
    ties
    stats1 {
      avg
    }
    stats2 {
      avg
    }
  }
}
